server {
    listen 80;
    # Diz para o Nginx usar o DNS nativo do Docker para achar os containers
    resolver 127.0.0.11 valid=10s;

    location /rest/v1/ {
        set $rest http://rest:3000;
        rewrite ^/rest/v1/(.*)$ /$1 break;
        proxy_pass $rest;
    }

    location /auth/v1/ {
        set $auth http://auth:9999;
        rewrite ^/auth/v1/(.*)$ /$1 break;
        proxy_pass $auth;
    }

    location /storage/v1/ {
        set $storage http://storage:5000;
        rewrite ^/storage/v1/(.*)$ /$1 break;
        proxy_pass $storage;
    }
}
